### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by cthoyt** [KramerChristian/NonadditivityAnalysis#2]
There isn't currently a LICENSE file in this repo, which makes reuse very difficult. It would be nice if you could add one, ideally under a permissive license like MIT or similar

On the bottom of the readme it says `The mmpdb package is copyright 2015-2017 by F. Hoffmann-La Roche Ltd and distributed under the 3-clause BSD license` but this does not really make sense for this whole repo

**Comment by KramerChristian** [comment]
Hi Charles. I have added a 3-clause BSD license file to the repo and fixed the statement about the license at the end of the code. Does this meet what you need?

Bests,
Christian

**Comment by cthoyt** [comment]
Yes, this is great. Thank you. This issue was closed by #3.
