### ISSUE TITLE
Upload packaged code to PyPI

### ISSUE THREAD

**Issue by cthoyt** [KramerChristian/NonadditivityAnalysis#4]
This will be a follow-up to #1 - after the code is properly packaged, the obvious next step is to upload it to PyPI so people can easily get it themselves.

@KramerChristian since you mentioned you don't have a lot of bandwidth at the moment to work on this, perhaps after I send a PR for #1, you might consider adding me as a collaborator on the repo, and I can take care uploading it to PyPI as well.

**Comment by KramerChristian** [comment]
@cthoyt Sure, I would be happy to do so. Thanks for taking this on!

**Comment by cthoyt** [comment]
@KramerChristian now that the code is packaged, do you want me to set it up so you can easily upload it to PyPI yourself, or do you want me to take care of it? Either way, you should make yourself an account on PyPI. If you have me take care of it, I’ll make you the administrator after.

**Comment by KramerChristian** [comment]
@cthoyt : It would be great if you could upload and register it on PyPI. I have just created an account there, my username is KramerChristian.

**Comment by cthoyt** [comment]
All done! You should have received an email to associate your account with the package

https://pypi.org/project/nonadditivity/

There are a few more tweaks I'd like to make to the project in terms of code reusability - I'll send PRs for those. If you'd rather not worry about reviewing them in a row, you could just add me as a collaborator and I'll push right to the main branch
